"""Evidence-safe components for stateful trading-policy reconstruction.

The package deliberately keeps public market observations, candidate policy
state, and recorded ledger observations separate. It does not alter the
canonical ledger or Phase 7C alignment artifacts.
"""

from .benchmarks import (
    PLANTED_BENCHMARK_REGISTRY,
    BenchmarkResult,
    generate_planted_threshold_trades,
    generate_planted_trades,
    planted_bar_threshold_policy,
    planted_clock_only_policy,
    planted_conjunction_policy,
    planted_cooldown_state_policy,
    planted_null_stochastic_policy,
    planted_observational_equivalence_pair,
    planted_out_of_family_policy,
    planted_pending_delayed_fill_policy,
    planted_regime_switching_policy,
    planted_reversal_policy,
    planted_tick_first_crossing_policy,
    planted_trailing_exit_policy,
    run_single_planted_benchmark,
    threshold_fixture_policy,
)
from .clocks import CompletedBarClock, QuoteClock, TimerClock
from .event_models import (
    CompletedBarModelB2,
    ContinuousPoissonB0,
    CausalTickModelB3,
    DiurnalCalendarB1,
    HawkesSelfExcitingB5,
    JointBarTickModelB4,
    compute_bits_per_event,
)
from .evidence import CANONICAL_LEDGER_SHA256, audit_canonical_evidence, build_decision_epochs, load_canonical_records
from .features import build_causal_feature_frame
from .identifiability import (
    EquivalenceClass,
    IdentifiabilitySummary,
    PlaceboTestResult,
    ReconstructionVerdict,
    cluster_equivalence_classes,
    determine_identifiability_verdict,
    generate_divergence_casebook,
    run_placebo_sensitivity_test,
)
from .matching import MatchConfig, match_entries
from .policy_ast import (
    Action,
    AndCondition,
    Condition,
    CrossesAboveCondition,
    CrossesBelowCondition,
    ExitRule,
    NotCondition,
    OrCondition,
    PersistsCondition,
    Policy,
    PriceDistanceExit,
    StateCondition,
    ThresholdCondition,
    TimeExit,
    TimeWindowCondition,
    TrailingStopExit,
    calculate_mdl_code_length,
)
from .replay import Quote, ReplayEngine, SimulatedTrade
from .reporting import (
    export_reconstructed_policy_package,
    generate_final_verdict_markdown,
    generate_placebo_calibration_markdown,
    generate_residual_casebook_markdown,
)
from .scoring import entry_error_loss
from .search import CandidateEvaluation, evaluate_policy, evaluate_policy_cohort
from .state_search import enumerate_stateful_policies, search_stateful_policies
from .synthesis import (
    SearchBudget,
    candidate_registry,
    enumerate_crossing_policies,
    enumerate_exit_rules,
    enumerate_t0_policies,
    enumerate_t1_conjunction_policies,
    enumerate_time_window_policies,
    synthesize_beam_search,
    threshold_grid,
)
from .validation import make_expanding_folds

__all__ = [
    "Action",
    "AndCondition",
    "BenchmarkResult",
    "CANONICAL_LEDGER_SHA256",
    "CausalTickModelB3",
    "CompletedBarClock",
    "CompletedBarModelB2",
    "Condition",
    "ContinuousPoissonB0",
    "CrossesAboveCondition",
    "CrossesBelowCondition",
    "DiurnalCalendarB1",
    "EquivalenceClass",
    "ExitRule",
    "HawkesSelfExcitingB5",
    "IdentifiabilitySummary",
    "JointBarTickModelB4",
    "MatchConfig",
    "NotCondition",
    "OrCondition",
    "PLANTED_BENCHMARK_REGISTRY",
    "PersistsCondition",
    "PlaceboTestResult",
    "Policy",
    "PriceDistanceExit",
    "Quote",
    "QuoteClock",
    "ReconstructionVerdict",
    "ReplayEngine",
    "SearchBudget",
    "SimulatedTrade",
    "StateCondition",
    "ThresholdCondition",
    "TimeExit",
    "TimeWindowCondition",
    "TimerClock",
    "TrailingStopExit",
    "audit_canonical_evidence",
    "build_causal_feature_frame",
    "build_decision_epochs",
    "calculate_mdl_code_length",
    "candidate_registry",
    "cluster_equivalence_classes",
    "compute_bits_per_event",
    "determine_identifiability_verdict",
    "entry_error_loss",
    "enumerate_crossing_policies",
    "enumerate_exit_rules",
    "enumerate_stateful_policies",
    "enumerate_t0_policies",
    "enumerate_t1_conjunction_policies",
    "enumerate_time_window_policies",
    "evaluate_policy",
    "evaluate_policy_cohort",
    "export_reconstructed_policy_package",
    "generate_divergence_casebook",
    "generate_final_verdict_markdown",
    "generate_placebo_calibration_markdown",
    "generate_planted_threshold_trades",
    "generate_planted_trades",
    "generate_residual_casebook_markdown",
    "load_canonical_records",
    "make_expanding_folds",
    "match_entries",
    "planted_bar_threshold_policy",
    "planted_clock_only_policy",
    "planted_conjunction_policy",
    "planted_cooldown_state_policy",
    "planted_null_stochastic_policy",
    "planted_observational_equivalence_pair",
    "planted_out_of_family_policy",
    "planted_pending_delayed_fill_policy",
    "planted_regime_switching_policy",
    "planted_reversal_policy",
    "planted_tick_first_crossing_policy",
    "planted_trailing_exit_policy",
    "run_placebo_sensitivity_test",
    "run_single_planted_benchmark",
    "search_stateful_policies",
    "synthesize_beam_search",
    "threshold_fixture_policy",
    "threshold_grid",
]
